<span style="margin-right: 5px;">
<?php echo $this->__(
    "Don't forget to set your shipping method to use KWIXO in the best way"
); ?> -
</span>
<a target="_blank" href="<?php echo Mage::helper('adminhtml/data')->getUrl(
    'adminhtml/kwixoshipping'
); ?>">
    <?php echo $this->__('Kwixo shipping setting'); ?>
</a>

<br/>

<a target="_blank" href="<?php echo Mage::helper('adminhtml/data')->getUrl(
    'adminhtml/kwixocategory'
); ?>">
    <?php echo $this->__('Kwixo Category Mapping'); ?>
</a>
<span style="margin-left: 5px;">
    <?php echo $this->__(
        'Please note that a proper category mapping is necessary in order to use this payment method'
    ); ?>.
</span>